- name: Check if Template VM Exists
  ansible.builtin.command: "qm status {{ vm_id }}"
  ignore_errors: true
  register: template_exists
  changed_when: false

- name: Debug Output
  ansible.builtin.debug:
    var: template_exists

- name: Debug Condition
  ansible.builtin.debug:
    var: "{{ play_hosts | map('extract', hostvars, 'template_exists') | selectattr('failed', '==', false) | list | count }}"

# TODO Add install qemu-guest-agent
- name: Create VM Template if it Does not Exist
  run_once: true
  # Only execute if template vm is found on none of the proxmox hosts
  # NOTE: Assumes you are running this on proxmox hosts all in a single cluster
  when: play_hosts | map('extract', hostvars, 'template_exists') | selectattr('failed', '==', false) | list | count == 0
  block:
    - name: Download CloudInit Image
      ansible.builtin.get_url:
        url: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
        dest: /root/jammy-server-cloudimg-amd64.img
        mode: u=rw,g=rw,o=r

    - name: Create VM
      ansible.builtin.command: "qm create {{ vm_id }} --memory {{ default_memory }} --core {{ default_cores }} --name {{ image_name }} --net0 virtio,bridge={{ default_network }}"
      changed_when: false

    - name: Import CloudInit Image
      ansible.builtin.command: "qm importdisk {{ vm_id }} /root/jammy-server-cloudimg-amd64.img {{ default_storage }}"
      changed_when: false

    - name: Attach New Disk to VM
      ansible.builtin.command: "qm set {{ vm_id }} --scsihw virtio-scsi-pci --scsi0 {{ default_storage }}:vm-{{ vm_id }}-disk-0"
      changed_when: false

    - name: Attach CloudInit Drive
      ansible.builtin.command: "qm set {{ vm_id }} --ide2 {{ default_storage }}:cloudinit"
      changed_when: false

    - name: Make CloudInit Bootable
      ansible.builtin.command: "qm set {{ vm_id }} --boot c --bootdisk scsi0"
      changed_when: false

    - name: Add Serial Console
      ansible.builtin.command: "qm set {{ vm_id }} --serial0 socket --vga serial0"
      changed_when: false

    - name: Configure CloudInit
      ansible.builtin.command: "qm set {{ vm_id }} --ciuser \"{{ default_user }}\""
      changed_when: false

    - name: Convert VM to Template
      ansible.builtin.command: "qm template {{ vm_id }}"
      changed_when: false
  rescue:
    - name: Remove Malformed VM Template
      ansible.builtin.command: "qm destroy {{ vm_id }}"
      changed_when: false
