all:
  vars:
    ansible_host: "{{inventory_hostname}}.{{host_domain}}"
    ansible_user: ansible
  children:
    proxmox:
      hosts:
        kratos:
        proxmox-lkld:
        backups-lkld:
      vars:
        ansible_user: root
    vms:
      hosts:
        docker-atl:
        plex-atl:
        pihole-atl:
        talos-atl:
        nginx-atl:
        pihole-lkld:
        nginx-lkld:
        k3s-atl:
    atlanta:
      hosts:
        kratos:
        docker-atl:
        plex-atl:
        pihole-atl:
        talos-atl:
        nginx-atl:
        k3s-atl:
        k3s-worker-0:
      vars:
        host_domain: infrastructure
    lakeland:
      hosts:
        pihole-lkld:
        nginx-lkld:
        proxmox-lkld:
        backups-lkld:
      vars:
        host_domain: lakeland
    pihole:
      hosts:
        pihole-atl:
          sync: primary
        pihole-lkld:
          sync: secondary
    plex:
      hosts:
        plex-atl:
    k3s:
      children:
        k3s-controllers:
          hosts:
            k3s-atl:
        k3s-workers:
          hosts:
            k3s-worker-0: