- name: Remove Old Docker Verisons
  ansible.builtin.apt:
    pkg:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
- name: Install Prerequisites
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
- name: Check if GPG key is already installed
  ansible.builtin.stat:
    path: /etc/apt/trusted.gpg.d/docker.gpg
  register: docker_gpg_stat
- name: Install Docker GPG Key
  ansible.builtin.shell: set -o pipefail && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/trusted.gpg.d/docker.gpg
  when: not docker_gpg_stat.stat.exists
- name: Get Architecture
  ansible.builtin.command: dpkg --print-architecture
  register: deb_architecture
  changed_when: false
- name: Get Release
  ansible.builtin.command: lsb_release -cs
  register: deb_release
  changed_when: false
- name: Add Docker apt repo
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ deb_architecture.stdout }} signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/ubuntu {{ deb_release.stdout }} stable"
- name: Install Docker
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-compose-plugin
      - docker-ce-cli
      - containerd.io
    update_cache: true
- name: Install Docker Python SDK
  ansible.builtin.pip:
    name: docker

- name: Install Docker Compose
  ansible.builtin.pip:
    name: docker-compose
