#!/usr/bin/env ansible-playbook

- name: Configure NGINX Proxy Manager
  hosts: "{{ targets }}"
  become: true
  roles:
    - vm-common
    - docker-host
  vars:
    targets: "nginx"
  tasks:
    - name: Copy Compose File
      template:
        src: templates/nginx-proxymanager.yml.j2
        dest: /home/ansible/nginx-proxymanager.yml
    - name: Spin Up Services
      community.docker.docker_compose:
        project_src: /home/ansible
        project_name: nginx-proxymanager
        files:
          - nginx-proxymanager.yml