- name: Update All Packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: true

- name: Ensure QEMU Guest Agent is Installed
  ansible.builtin.apt:
    name: qemu-guest-agent
    state: present

- name: Ensure QEMU Guest Agent is Enabled
  ansible.builtin.systemd:
    name: qemu-guest-agent
    state: started
    enabled: true

- name: Disable SSH Delete Keys
  ansible.builtin.lineinfile:
    path: /etc/cloud/cloud.cfg
    regexp: '^ssh_deletekeys: '
    line: 'ssh_deletekeys: false'

- name: Check if restart is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_file

- name: Reboot if required
  ansible.builtin.reboot:
  when: reboot_file.stat.exists
