- name: Update All Packages
  apt:
    update_cache: true
    upgrade: true

- name: Ensure QEMU Guest Agent is Installed
  apt:
    name: qemu-guest-agent
    state: present

- name: Ensure QEMU Guest Agent is Enabled
  systemd:
    name: qemu-guest-agent
    state: started
    enabled: yes

- name: Check if restart is required
  stat:
    path: /var/run/reboot-required
  register: reboot_file

- name: Reboot if required
  reboot:
  when: reboot_file.stat.exists
