#!/usr/bin/env ansible-playbook

- name: Configure Proxmox
  hosts: proxmox
  tasks:
    - name: Ensure Enterprise Repo is Removed
      apt_repository:
        repo: deb https://enterprise.proxmox.com/debian/pve bullseye pve-enterprise
        state: absent

    - name: Ensure No-Subscription Repo is Enabled
      apt_repository:
        repo: deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription
        state: present

    - name: Update Package Repositories
      apt:
        update_cache: yes

    - name: Upgrade All Packages
      apt:
        upgrade: yes

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: p

    - name: Reboot Server if Required
      reboot:
      when: p.stat.exists

    - name: Enable PCI Passthrough in GRUB
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
        line: GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_iommu=on"
      register: grub

    - name: Update GRUB
      shell: update-grub
      when: grub.changed

    - name: Enable PCI Passthrough Kernel Modules
      lineinfile:
        path: /etc/modules
        line: "{{ item }}"
        state: present
      with_items:
        - vfio
        - vfio_iommu_type1
        - vfio_pci
        - vfio_virqfd
      register: modules

    - name: Update Kernel Modules
      shell: update-initramfs -u -k all
      when: modules.changed

    - name: Reboot Server if Required
      reboot:
      when: modules.changed or grub.changed

