#!/usr/bin/env ansible-playbook

- name: Configure NGINX Proxy Manager
  hosts: "{{ targets }}"
  become: true
  roles:
    - vm-common
    - docker-host
  vars:
    targets: "nginx"
  tasks:
    - name: Copy Compose File
      copy:
        src: docker-compose-files/nginx-proxymanager.yml
        dest: /home/ansible/nginx-proxymanager.yaml
    - name: Spin Up Services
      shell: docker compose -f /home/ansible/nginx-proxymanager.yaml up -d