#!/usr/bin/env ansible-playbook

- name: Configure Ombi Docker Stack
  hosts: "{{ targets }}"
  become: true
  roles:
    - vm-common
    - docker-host
  vars:
    targets: "docker"
  tasks:
    - name: Copy Compose File
      copy:
        src: docker-compose-files/ombi.yml
        dest: /home/ansible/ombi.yaml
    - name: Spin Up Services
      community.docker.docker_compose:
        project_src: /home/ansible
        project_name: ombi
        files:
          - ombi.yaml