#!/usr/bin/env ansible-playbook

- name: Configure Proxmox
  hosts: proxmox
  roles:
    - role: cloudinit-template
      vars:
        default_storage: "local-zfs"
  handlers:
    - name: Update GRUB
      ansible.builtin.command: update-grub
    - name: Update Kernel Modules
      ansible.builtin.command: update-initramfs -u -k all
  tasks:
    - name: Ensure Enterprise Repo is Removed
      ansible.builtin.apt_repository:
        repo: deb https://enterprise.proxmox.com/debian/pve bullseye pve-enterprise
        state: absent

    - name: Ensure No-Subscription Repo is Enabled
      ansible.builtin.apt_repository:
        repo: deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription
        state: present

    - name: Update Package Repositories
      ansible.builtin.apt:
        update_cache: true
        upgrade: true

    - name: Enable PCI Passthrough in GRUB
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
        line: GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_iommu=on"
      notify:
        - Update GRUB

    - name: Enable PCI Passthrough Kernel Modules
      ansible.builtin.lineinfile:
        path: /etc/modules
        line: "{{ item }}"
        state: present
      with_items:
        - vfio
        - vfio_iommu_type1
        - vfio_pci
        - vfio_virqfd
      notify:
        - Update Kernel Modules

    - name: Check if reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: p

    - name: Reboot Server if Required
      ansible.builtin.reboot:
      when: p.stat.exists
