#!/usr/bin/env ansible-playbook

- name: Setup Plex
  hosts: "{{ targets }}"
  become: true
  roles:
    - vm-common
  vars_prompt:
    # Root NFS path (10.0.0.50:/mnt/Vault/Media) /Movies /TV /Music will be appended to root
    - name: nfs_root
      prompt: NFS Root Path
  vars:
    targets: "plex"
  tasks:
    - name: Install Dependencies
      apt:
        name: nfs-common
    - name: Add Mount Points
      mount:
        src: "{{ (nfs_root, item) | path_join }}"
        path: "/mnt/{{item}}"
        state: mounted
        fstype: nfs
      loop:
        - Movies
        - TV
        - Music

    - name: Add Plex Official Repo
      block:
      - name: Fetch Key 
        get_url:
          url: https://downloads.plex.tv/plex-keys/PlexSign.key
          dest: /etc/apt/trusted.gpg.d/plex.asc
      - name: Add Repository
        apt_repository:
          repo: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/plex.asc] https://downloads.plex.tv/repo/deb public main

    - name: Install Plex
      apt:
        update_cache: true
        name: plexmediaserver