#!/usr/bin/env ansible-playbook

- name: Setup Plex
  hosts: "{{ targets }}"
  become: true
  roles:
    - vm-common
  vars_prompt:
    # Root NFS path (10.0.0.50:/mnt/Vault/Media) /Movies /TV /Music will be appended to root
    - name: nfs_root
      prompt: NFS Root Path
      private: false
  vars:
    targets: "plex"
  tasks:
    - name: Install Dependencies
      ansible.builtin.apt:
        name: nfs-common
    - name: Add Mount Points
      ansible.posix.mount:
        src: "{{ (nfs_root, item) | path_join }}"
        path: "/mnt/{{ item }}"
        state: mounted
        fstype: nfs
      loop:
        - Movies
        - TV
        - Music

    - name: Add Plex Official Repo
      block:
        - name: Fetch Key
          ansible.builtin.get_url:
            url: https://downloads.plex.tv/plex-keys/PlexSign.key
            dest: /etc/apt/trusted.gpg.d/plex.asc
            mode: u=rw,g=r,o=r
        - name: Add Repository
          ansible.builtin.apt_repository:
            repo: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/plex.asc] https://downloads.plex.tv/repo/deb public main

    - name: Install Plex
      ansible.builtin.apt:
        update_cache: true
        name: plexmediaserver
