#!/usr/bin/env ansible-playbook

- name: Configure Pirate Ship Docker Stack
  hosts: "{{ targets }}"
  become: true
  roles:
    - vm-common
    - docker-host
  vars:
    targets: "docker"
    template_tz: "America/New_York"
    nfs_host: "10.0.0.50"
    nfs_movies_path: "/mnt/Vault/Media/Movies"
    nfs_tv_path: "/mnt/Vault/Media/TV"
    nfs_downloads_path: "/mnt/Vault/Media/downloads"
    vpn_region: "US Florida"
  vars_prompt:
    - name: pia_username
      private: false
      prompt: PIA Username
    - name: pia_password
      private: true
      prompt: PIA Password
  tasks:
    - name: Copy Compose File
      copy:
        src: templates/docker-compose-files/pirate-ship.yml.j2
        dest: /home/ansible/pirate-ship.yml
    - name: Spin Up Services
      community.docker.docker_compose:
        project_src: /home/ansible
        project_name: pirate-ship
        files:
          - pirate-ship.yml
      environment:
        USER: "{{ pia_username }}"
        PASSWORD: "{{ pia_password }}"
        TZ: "{{ template_tz }}"
        NFS_HOST: "{{ nfs_host }}"
        NFS_MOVIES_PATH: "{{ nfs_movies_path }}"
        NFS_TV_PATH: "{{ nfs_tv_path }}"
        NFS_DOWNLOADS_PATH: "{{ nfs_downloads_path }}"
        VPN_REGION: "{{ vpn_region }}"