#!/usr/bin/env ansible-playbook

- name: Configure PiHole
  hosts: "{{ targets }}"
  become: true
  roles:
    - vm-common
  vars_prompt:
    - name: password
      prompt: Web password
      private: true
  vars:
    targets: "pihole"
  tasks:
    - name: Hash Password
      ansible.builtin.shell: "set -o pipefail && echo -n {{ password }} | sha256sum | awk '{printf \"%s\",$1 }' | sha256sum | awk '{printf \"%s\",$1}'"
      register: hashed_password_shell
      changed_when: false
    - name: Set Hashed Password
      ansible.builtin.set_fact:
        hashed_password: "{{ hashed_password_shell.stdout }}"
    - name: Make Sure PiHole Dir Exists
      ansible.builtin.file:
        path: /etc/pihole
        state: directory
        mode: u=rwx,g=rwx,o=rx
    - name: Create setupVars.conf
      ansible.builtin.template:
        src: templates/pihole-setupVars.j2
        dest: /etc/pihole/setupVars.conf
        mode: u=rw,g=r,o=r
    - name: Run Install Script
      ansible.builtin.shell: set -o pipefail && curl -L https://install.pi-hole.net | bash /dev/stdin --unattended
      changed_when: false
