k3s_version: v1.22.3+k3s1
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['k3s-controllers'][0]]['ansible_host'] | default(groups['k3s-controllers'][0]) }}"
extra_server_args: "--disable servicelb --disable local-storage"
extra_agent_args: ""